### ISSUE TITLE
Django-Payzen not Django 1.10 ready: templatetags/payzen_extras.py throws 'context must be a dict rather than Context'.

### ISSUE THREAD

**Issue by webinventdotcom** [bsvetchine/django-payzen#6]
Hi,
The tag payzen_form from the templatetags.payzen_extras.py file is not compatible with django 1.10. According to https://docs.djangoproject.com/en/1.10/topics/templates/#django.template.backends.base.Template.render and https://stackoverflow.com/questions/43787700/django-1-11-typeerror-context-must-be-a-dict-rather-than-context the returned context should be a dict instead of a Context.
I get this in my project:
`TypeError at /checkout/payment-details/
context must be a dict rather than Context...
C:\virtualenv\oscar\lib\site-packages\django_payzen\templatetags\payzen_extras.py in payzen_form
        "payzen_submit_url": app_settings.PAYZEN_REQUEST_URL`

In the _payzen_extras.py_ file line 18 the code is:
`return t.render(template.Context({...`

https://github.com/bsvetchine/django-payzen/blob/master/django_payzen/templatetags/payzen_extras.py

It would be a simple fix to simply return a dict instead of the Context.
Geoffroy

**Comment by bsvetchine** [comment]
Hello,

Thank you for reporting this issue ! I pushed this commit which should fix it ;
https://github.com/bsvetchine/django-payzen/commit/944c3026120151495310cb1eb3c6370dc2db3db9

**Comment by webinventdotcom** [comment]
Thanks ! It works now !
